# Data
train_file: data/sem_eval/SemEval2010_task8_training/TRAIN_FILE.TXT
test_file: data/sem_eval/SemEval2010_task8_testing_keys/TEST_FILE_FULL.TXT
normalization:
  - lowercase
  - html
  - urls
# Model
transformer: bert-large-uncased
# Training
mini_batch_size: 4
batch_size: 64
lr: 0.00003
resume: False
